### ISSUE TITLE
Sample State, Frontend & Backend Routes

### ISSUE THREAD

**Issue by paulobocanegra** [LetsGitFunky/Artsy#2]
# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + The author username and imageurl for a post. Basically any info that the user can't change
        + Like count and a boolean on whether the user likes the post instead of a likes slice

---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [ ] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by paulobocanegra** [comment]
Backend Routes:
The only way GET /api/users would get us data for 1 user is if we used resource instead of resources and it would be GET /api/user. We definitely don't want to do that. GET /api/users would get you the index, and you may want to get users. Add a GET /api/users/id to get a specific user with the id.

**Comment by paulobocanegra** [comment]
Frontend Routes:

the index of reviews should be nested under a product show page. Therefore, we need a /products/:productId frontend route where we will have the ProductShowPage and this will be the parend of ReviewIndex & ReviewIndexItem

**Comment by LetsGitFunky** [comment]
made the edits specified. The reviews are pretty deeply nested, so let me
know what you think. thanks!

**Comment by paulobocanegra** [comment]
Excellent work!
